### ISSUE TITLE
repmon's grid of "replication documents" needs manual refresh

### ISSUE THREAD

**Issue by bitsandbytes** [mobdata/replication#27]
When I log into repmon the Replication Documents grid is always empty, even when I know there should be data in it. If I refresh the page it will then be populated.

**Comment by rudyj03** [comment]
After some more research, the problem came down to defining a width on the div ui-grid is rendered on.  There are actually a few ways to handle the problem, as outlined here http://ui-grid.info/docs/#/tutorial/108_hidden_grids  The easiest being setting a css class with a default width (100% in our case)
